version: "3"
services:
  fastapi:
    build:
      context: ./np/fastapi
    image: seoyerin307/fastapi-app:latest
    ports:
      - "8080:8080"
    networks:
      - app-network

  node:
      build:
        context: ./np/node
      dimage: seoyerin307/node-app:latest
      ports:
        - "3000:3000"
      networks:
      - app-network
      depends_on:
        - fastapi

networks:
  app-network:
    driver: bridge
 