services:
  fastapi:
    build:
      context: ./np/fastapi
    # image: seoyerin307/fastapi-app:latest
    ports:
      - "8080:8080"
    # env_file:
    #   - ./fastapi-backend/.env
    networks:
      - app-network

  node:
      build:
        context: ./np/node
      image: seoyerin307/node-app:latest
      ports:
        - "3001:3000"
      networks:
      - app-network
      depends_on:
        - fastapi

networks:
  app-network:
    driver: bridge
 