name: Deploy Node.js MVC App to EC2

on:
  push:
    branches:
      - main

env:
  DOCKER_HUB_USERNAME: ${{ secrets.DOCKER_HUB_USERNAME }}
  DOCKER_HUB_TOKEN: ${{ secrets.DOCKER_HUB_TOKEN }}
  APP_DOCKER_IMAGE_NAME: seoyerin307/node-app
  AWS_REGION: ap-southeast-2
  EC2_HOST: ${{ secrets.HOST }}
  EC2_USERNAME: ${{ secrets.USERNAME }}
  EC2_KEY: ${{ secrets.KEY }}

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ env.DOCKER_HUB_USERNAME }}
          password: ${{ env.DOCKER_HUB_TOKEN }}

      - name: Build and Push Docker Image
        uses: docker/build-push-action@v5
        with:
          context: ./np
          file: ./np/Dockerfile
          push: true
          tags: ${{ env.APP_DOCKER_IMAGE_NAME }}:latest

      - name: Deploy to EC2
        uses: appleboy/ssh-action@master
        with:
          host: ${{ env.EC2_HOST }}
          username: ${{ env.EC2_USERNAME }}
          key: ${{ env.EC2_KEY }}
          port: ${{ secrets.PORT }}
          script: |
            echo "--- Pulling Latest App Image ---"
            docker pull ${{ env.APP_DOCKER_IMAGE_NAME }}:latest

            echo "--- Stopping and Removing Old App Container ---"
            docker stop node-app || true
            docker rm node-app || true

            echo "--- Running New App Container ---"
            docker run -d --restart always --name node-app -p 3000:3000 ${{ env.APP_DOCKER_IMAGE_NAME }}:latest

            echo "--- Cleaning up unused Docker images ---"
            docker system prune -f